services:
  flutter-web:
    image : flutter-web-app:latest
    build: .
    ports: # Port forwarding, [host]:[container]
      - "80:80"
      - "443:443"
    # Shared network for Backend & Frontend
    networks:
      - SectraNet


# External network to connect the frontend and backend containers together
# This network has to be created manually with the command "docker network create SectraNet"
networks:
  SectraNet:
    external: true